name: Release tag

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "patch | minor | major"
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: swiftty/nextversion@v0.0.1
        id: nextversion
        with:
          bump: ${{ github.event.inputs.version }}
          tag_prefix: v
      - name: git settings
        run: |
          # https://qiita.com/thaim/items/3d1a4d09ec4a7d8844ce
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: update default.json
        run: |
          sed -i -E 's|(swiftty\/renovate-config\/\/[^#]+)#(v?[0-9]+\.[0-9]+\.[0-9]+)|\1#${{ steps.nextversion.outputs.next }}|g' default.json

          git add default.json
          git commit -m 'update default.json'
          git push origin main
      - uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          tag_name: ${{ steps.nextversion.outputs.next }}
